local https = require("ssl.https")
local ltn12 = require("ltn12")
local logger = require("logger")
local CacheManager = require("image_cache_manager")

local PollinationsClient = {}

-- Pollinations.ai Image Generation - gen.pollinations.ai API v0.3.0
-- enhance=true lets the model understand any language (including Arabic) natively
local BASE_URL = "https://gen.pollinations.ai/image"

-- turbo = fastest model, best for E-ink quick previews
PollinationsClient.DEFAULT_MODEL = "turbo"

-- E-ink optimized suffix: high contrast, grayscale-friendly, sharp lines
local EINK_SUFFIX = ", high contrast, black and white illustration, sharp lines, "
    .. "no gradients, bold outlines, ink drawing style, crisp details"

function PollinationsClient.generateImage(prompt, api_key, options)
    if not prompt or prompt == "" then
        return nil, "Prompt cannot be empty."
    end
    if not api_key or api_key == "" then
        return nil, "API Key is required. Get one at enter.pollinations.ai"
    end

    options = options or {}
    local model  = options.model  or PollinationsClient.DEFAULT_MODEL
    -- E-ink Kindle screens: 758×1024 (Paperwhite) portrait ratio
    local width  = options.width  or 512
    local height = options.height or 680
    local eink   = options.eink ~= false  -- default: true

    -- enhance=true: the API automatically improves and understands the prompt
    -- (works with Arabic and other non-English languages natively)
    local final_prompt = prompt
    if eink then
        final_prompt = final_prompt .. EINK_SUFFIX
    end

    logger.info("Pollinations: model=" .. model .. " prompt=" .. final_prompt)

    -- URL-encode the prompt
    local escaped_prompt = final_prompt:gsub("([^%w%.%-%_])", function(c)
        return string.format("%%%02X", string.byte(c))
    end)

    local url = BASE_URL .. "/" .. escaped_prompt
        .. "?model="  .. model
        .. "&width="  .. tostring(width)
        .. "&height=" .. tostring(height)
        .. "&nologo=true"
        .. "&enhance=true"

    logger.info("Pollinations: requesting URL=" .. url)

    local response_chunks = {}
    local ok, code, response_headers, status_line = https.request{
        url    = url,
        method = "GET",
        headers = {
            ["Authorization"] = "Bearer " .. api_key,
            ["Accept"]        = "image/jpeg, image/png, */*",
        },
        sink = ltn12.sink.table(response_chunks),
    }

    if not ok then
        return nil, "Network error: " .. tostring(code or status_line or "connection failed")
    end

    code = tonumber(code) or 0
    if code ~= 200 then
        if code == 401 then return nil, "Invalid API Key (401). Get one at enter.pollinations.ai" end
        if code == 402 then return nil, "Insufficient pollen balance (402). Check enter.pollinations.ai" end
        if code == 403 then return nil, "Access denied (403). Check your API key permissions." end
        if code == 400 then return nil, "Bad request (400). Try a different prompt." end
        return nil, "API Error " .. tostring(code) .. ": " .. tostring(status_line or "Unknown")
    end

    local image_content = table.concat(response_chunks)
    if not image_content or #image_content == 0 then
        return nil, "Empty response from Pollinations API"
    end
    logger.info("Pollinations: received " .. tostring(#image_content) .. " bytes")

    -- File extension from Content-Type
    local ext = ".jpg"
    if response_headers then
        local ct = (response_headers["content-type"] or response_headers["Content-Type"] or ""):lower()
        if ct:find("png") then ext = ".png" end
    end

    -- Save to cache
    local cache_dir = CacheManager.getCacheDir()
    if not cache_dir then
        return nil, "Failed to get cache directory"
    end
    local filename  = "pollinations_" .. os.time() .. "_" .. math.random(1000, 9999) .. ext
    local full_path = cache_dir .. "/" .. filename

    local f, ferr = io.open(full_path, "wb")
    if not f then
        return nil, "Failed to save image: " .. tostring(ferr or "unknown")
    end
    f:write(image_content)
    f:close()

    logger.info("Pollinations: saved to " .. full_path)

    -- Show original Arabic prompt as title if translated
    local display_title = prompt

    return {
        {
            title         = display_title,
            description   = "Generated by Pollinations.ai (" .. model .. ")",
            thumbnail_url = "file://" .. full_path,
            full_url      = "file://" .. full_path,
            is_local      = true,
            local_path    = full_path,
        }
    }
end

return PollinationsClient
